const problems=[
{id:'parking',title:'Parking Lot',level:'Intermediate',desc:'Design a parking lot that supports different vehicle types, parking spots, ticketing, and fee calculation.',req:['Different vehicle sizes require compatible spots','A vehicle receives a ticket when parked','The system calculates a fee when a vehicle exits','The design should support adding pricing rules later']},
{id:'vending',title:'Vending Machine',level:'Beginner',desc:'Design a vending machine that manages products, inventory, payments, and dispensing.',req:['Products have prices and inventory','A user selects a product and pays','The machine handles insufficient payment','The machine returns change and updates inventory']},
{id:'elevator',title:'Elevator System',level:'Advanced',desc:'Design an elevator system that handles requests, scheduling, and multiple elevators.',req:['Multiple elevators may exist','Requests have source and destination floors','The system assigns requests to elevators','The design should allow scheduling strategies to evolve']},
{id:'library',title:'Library Management',level:'Intermediate',desc:'Design a library system for books, members, borrowing, returns, and overdue handling.',req:['Members can borrow available books','A book can have multiple copies','Returns update availability','Overdue rules can change independently']}
];
let current=null;
const $=id=>document.getElementById(id);
function renderProblems(){ $('problemGrid').innerHTML=problems.map(p=>`<div class="card"><h3>${p.title}</h3><span class="tag">${p.level}</span><p class="muted">${p.desc}</p><button onclick="start('${p.id}')">Start Practice</button></div>`).join(''); }
function start(id,existing){current=problems.find(p=>p.id===id); $('problemsView').classList.add('hidden');$('historyView').classList.add('hidden');$('resultView').classList.add('hidden');$('practiceView').classList.remove('hidden');$('practiceView').innerHTML=`<div class="sectionHead"><h2>${current.title}</h2><button class="secondary" onclick="showProblems()">Back</button></div><div class="problemInfo"><b>Problem</b><p>${current.desc}</p><b>Requirements</b><ul>${current.req.map(x=>`<li>${x}</li>`).join('')}</ul></div><div class="panel form"><label>Requirements / Assumptions</label><textarea id="assumptions" placeholder="State your assumptions and clarify requirements..."></textarea><label>Classes & Responsibilities</label><textarea id="classes" placeholder="List classes and what responsibility each class owns..."></textarea><label>Relationships / Design</label><textarea id="relationships" placeholder="Explain associations, interfaces, inheritance, composition, etc..."></textarea><label>Patterns / Reasoning</label><textarea id="patterns" placeholder="Explain patterns or design choices and why you chose them..."></textarea><label>Edge Cases</label><textarea id="edges" placeholder="List important edge cases and how your design handles them..."></textarea><div class="actions"><button onclick="submitAttempt()">Submit Solution</button></div></div>`;}
function evaluate(s){const text=Object.values(s).join(' ').toLowerCase();const checks=[['Requirement Understanding',s.assumptions, ['assumption','requirement','constraint']],['Class Responsibilities',s.classes,['class','responsibility','service','manager']],['Encapsulation & Interfaces',s.relationships,['interface','encapsulation','composition','dependency']],['Abstraction / Patterns',s.patterns,['strategy','factory','observer','pattern','abstraction']],['Extensibility',s.patterns+s.relationships,['extend','change','open/closed','interface','strategy']],['Edge Cases',s.edges,['edge','error','invalid','empty','failure']],['Explanation Quality',text,['because','trade-off','reason','why']]];return checks.map(([criterion,val,words])=>{const hits=words.filter(w=>String(val).toLowerCase().includes(w)).length;const score=Math.min(5,Math.max(2,hits+2));const evidence=hits?`Your submission explicitly mentions ${words.filter(w=>String(val).toLowerCase().includes(w)).slice(0,2).join(' and ')}.`:'The section does not contain enough explicit design evidence.';return {criterion,score,evidence,concern:score<4?'Add more concrete reasoning or responsibilities.':'The criterion is addressed clearly for the MVP.',suggestion:score<4?'Name the affected classes and explain why the responsibility belongs there.':'Keep the responsibility focused and explain how the design handles change.',confidence:score>=4?'High':'Medium'};});}
function submitAttempt(){const s={assumptions:$('assumptions').value.trim(),classes:$('classes').value.trim(),relationships:$('relationships').value.trim(),patterns:$('patterns').value.trim(),edges:$('edges').value.trim()};if(Object.values(s).some(v=>!v)){alert('Please complete all five sections before submitting.');return;}const attempt={id:Date.now(),problemId:current.id,problem:current.title,submittedAt:new Date().toISOString(),status:'Completed',submission:s,feedback:evaluate(s)};const h=JSON.parse(localStorage.getItem('lldAttempts')||'[]');h.unshift(attempt);localStorage.setItem('lldAttempts',JSON.stringify(h));showResult(attempt);}
function showResult(a){$('practiceView').classList.add('hidden');$('resultView').classList.remove('hidden');const total=a.feedback.reduce((x,f)=>x+f.score,0),max=a.feedback.length*5;$('resultView').innerHTML=`<div class="sectionHead"><h2>Evaluation — ${a.problem}</h2><button class="secondary" onclick="showProblems()">Problems</button></div><div class="panel"><span class="status">${a.status}</span><p class="summary"><b>Overall:</b> ${total}/${max}. Feedback is criterion-based so you can identify what to improve rather than relying only on a single score.</p>${a.feedback.map(f=>`<div class="feedback"><h4>${f.criterion} <span class="score">${f.score}/5</span></h4><p><b>Evidence:</b> ${f.evidence}</p><p><b>Concern:</b> ${f.concern}</p><p><b>Suggestion:</b> ${f.suggestion}</p><p class="muted"><b>Confidence:</b> ${f.confidence}</p></div>`).join('')}<div class="actions"><button onclick="start('${a.problemId}')">Try Again</button><button class="secondary" onclick="showHistory()">View History</button></div></div>`;}
function showHistory(){$('problemsView').classList.add('hidden');$('practiceView').classList.add('hidden');$('resultView').classList.add('hidden');$('historyView').classList.remove('hidden');const h=JSON.parse(localStorage.getItem('lldAttempts')||'[]');$('historyList').innerHTML=h.length?h.map(a=>`<div class="card historyItem"><b>${a.problem}</b><p class="muted">${new Date(a.submittedAt).toLocaleString()} • ${a.status}</p><p>Score: ${a.feedback.reduce((x,f)=>x+f.score,0)}/${a.feedback.length*5}</p><button onclick='showResult(${JSON.stringify(a)})'>Review Feedback</button></div>`).join(''):'<div class="panel">No attempts yet. Start your first practice problem.</div>';}
function showProblems(){$('historyView').classList.add('hidden');$('practiceView').classList.add('hidden');$('resultView').classList.add('hidden');$('problemsView').classList.remove('hidden');}
$('historyBtn').onclick=showHistory;$('backProblems').onclick=showProblems;renderProblems();
